src/ISAT.Developer.Exam.Web/Models/ErrorViewModel.cs
using System;

namespace ISAT.Developer.Exam.Web.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

src/ISAT.Developer.Exam.Web/Models/PersonViewModel.cs
using System.ComponentModel;

namespace ISAT.Developer.Exam.Web.Models
{
    public class PersonViewModel
    {
        public long Id { get; set; }

        [DisplayName("First name")]
        public string FirstName { get; set; }

        [DisplayName("Last name")]
        public string LastName { get; set; }

        [DisplayName("E-mail")]
        public string Email { get; set; }

        [DisplayName("Age")]
        public int Age { get; set; }

        public string getClass = "col-md-10 form-control";
    }
}

src/ISAT.Developer.Exam.Web/Controllers/BaseController.cs
using FluentValidation.Results;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Linq;

namespace ISAT.Developer.Exam.Web.Controllers
{
    public class BaseController : Controller
    {
        private readonly ICollection<string> _errors = new List<string>();

        protected bool ResponseHasErrors(ValidationResult validate)
        {
            if (validate == null || validate.IsValid) {
                return false;
            }

            foreach (var error in validate.Errors) {
                ModelState.AddModelError(string.Empty, error.ErrorMessage);
            }

            return true;
        }
    }
}

src/ISAT.Developer.Exam.Web/Controllers/HomeController.cs
using ISAT.Developer.Exam.Web.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace ISAT.Developer.Exam.Web.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult About()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

src/ISAT.Developer.Exam.Web/Controllers/PersonsController.cs
using System;
using System.Linq;
using System.Diagnostics;
using System.Threading.Tasks;
using System.Collections.Generic;

using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;

using ISAT.Developer.Exam.Web.Models;
using ISAT.Developer.Exam.Core.Entities;
using ISAT.Developer.Exam.Core.Services;
using ISAT.Developer.Exam.Core.Interfaces;

namespace ISAT.Developer.Exam.Web.Controllers
{
    public class PersonsController : BaseController
    {
        private readonly ILogger<PersonsController> _logger;

        private readonly IPersonService _personService;

        public PersonsController(ILogger<PersonsController> logger, IPersonService personService)
        {
            _logger = logger;
            _personService = personService;
        }

        public IActionResult Index()
        {
            var persons = _personService.GetAll();

            return View(persons.Select(person => new PersonViewModel()
            {
                Id        = person.Id,
                FirstName = person.FirstName,
                LastName  = person.LastName,
                Email     = person.Email,
                Age       = person.Age
            }));
        }

        [HttpGet]
        public IActionResult Create()
        {

            var personViewModel = new PersonViewModel();
            return View(personViewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create([Bind] PersonViewModel personViewModel)
        {
            if (!ModelState.IsValid) {
                return View(personViewModel);
            }

            var personEntity = Person.CreateNewPerson(personViewModel.FirstName, personViewModel.LastName, personViewModel.Email, personViewModel.Age);

            if (ResponseHasErrors(_personService.Insert(personEntity))) {
                return View(personViewModel);
            }

            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult Edit(long? id)
        {
            if (id == null) {
                return NotFound();
            }

            var personEntity = _personService.GetById(id.Value);
            if (personEntity == null) {
                return NotFound();
            }

            var personViewModel = new PersonViewModel()
            {
                Id        = personEntity.Id,
                FirstName = personEntity.FirstName,
                LastName  = personEntity.LastName,
                Email     = personEntity.Email,
                Age       = personEntity.Age,
            };

            return View(personViewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit([Bind] PersonViewModel personViewModel)
        {
            if (!ModelState.IsValid) {
                return View(personViewModel);
            }

            var personEntity = Person.ToPerson(personViewModel.Id, personViewModel.FirstName, personViewModel.LastName, personViewModel.Email, personViewModel.Age);

            if (ResponseHasErrors(_personService.Update(personEntity))) {
                return View(personViewModel);
            }

            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult Delete(long? id)
        {
            if (id == null) {
                return NotFound();
            }

            var personEntity = _personService.GetById(id.Value);
            if (personEntity == null) {
                return NotFound();
            }

            var personViewModel = new PersonViewModel()
            {
                Id        = personEntity.Id,
                FirstName = personEntity.FirstName,
                LastName  = personEntity.LastName,
                Email     = personEntity.Email,
                Age       = personEntity.Age,
            };

            return View(personViewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Delete([Bind] PersonViewModel personViewModel)
        {
            if (!ModelState.IsValid || ResponseHasErrors(_personService.Delete(personViewModel.Id))) {
                return View(personViewModel);
            }

            return RedirectToAction("Index");
        }
    }
}

src/ISAT.Developer.Exam.Web/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About John";
}
<h1>@ViewData["Title"]</h1>

<p>There are some trivia about John 🜏…</p>

src/ISAT.Developer.Exam.Web/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Hi!  I am <b>John</b> <i class="fas fa-user-astronaut"></i></h1>

    <p>You can see more informations about me on <a href="https://github.com/jmurowaniecki" target="_blank">my Github<i class="fab fa-github"></i></a> or in <a href="https://www.linkedin.com/in/lamdadeveloper" target="_blank">my LinkedIn <i class="fab fa-linkedin"></i></a></p>
</div>

src/ISAT.Developer.Exam.Web/Views/Persons/Create.cshtml
@model ISAT.Developer.Exam.Web.Models.PersonViewModel

@{
    ViewData["Title"] = "Create Person";
    ViewData["action"] = "Save";
}

<form asp-action="Create">
    @await Html.PartialAsync("./part/form.cshtml")
</form>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

src/ISAT.Developer.Exam.Web/Views/Persons/Delete.cshtml
@model ISAT.Developer.Exam.Web.Models.PersonViewModel

@{
    ViewData["Title"] = "Delete Person";
    ViewData["action"] = "Confirm deletion";
    ViewData["Person"] = Model.FirstName + " " + Model.LastName;
}

<form asp-action="Delete">
    <div class="row">
        <div class="col-sm">
            <h3>@ViewData["Title"]</h3>
        </div>
        <div class="col-sm">
            <input type="submit" value="@ViewData["action"] of @ViewData["Person"]" class="btn btn-danger" />
        </div>
        <div class="col-sm">
            @Html.ActionLink("…Return to list", "Index", null, null, new { @class = "btn btn-info" })
        </div>
    </div>
</form>

src/ISAT.Developer.Exam.Web/Views/Persons/Edit.cshtml
@model ISAT.Developer.Exam.Web.Models.PersonViewModel

@{
    ViewData["Title"] = "Edit Person";
    ViewData["action"] = "Update";
}

<form asp-action="Edit">
    <input type="hidden" asp-for="Id" />

    @await Html.PartialAsync("./part/form.cshtml")
</form>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

src/ISAT.Developer.Exam.Web/Views/Persons/Index.cshtml
@model IEnumerable<ISAT.Developer.Exam.Web.Models.PersonViewModel>

@{
    ViewData["Title"] = "Persons Management";
}

<div class="row">
    <div class="col-sm">
        <h3>@ViewData["Title"]</h3>
    </div>
    <div class="col-sm">
    </div>
    <div class="col-sm right">
        <a asp-action="Create" class="btn btn-primary">Create new person</a>
    </div>
</div>
<hr />
<div class="panel">
    <table class="table">
        <thead>
            <tr>
                <th>@Html.DisplayNameFor(model => model.Id)</th>
                <th>@Html.DisplayNameFor(model => model.FirstName)</th>
                <th>@Html.DisplayNameFor(model => model.LastName)</th>
                <th>@Html.DisplayNameFor(model => model.Email)</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
        @if (!Model.Any()) {
            <tr>
                <td colspan="5">No results found</td>
            </tr>
        }
        @foreach (var person in Model) {
            <tr>
                <td>@Html.DisplayFor(modelItem => person.Id)</td>
                <td>@Html.DisplayFor(modelItem => person.FirstName)</td>
                <td>@Html.DisplayFor(modelItem => person.LastName)</td>
                <td>@Html.DisplayFor(modelItem => person.Email)</td>
                <td>
                    <a asp-action="Edit"   asp-route-id="@person.Id" title="Edit"   class="btn btn-secondary">Edit</a>
                    <a asp-action="Delete" asp-route-id="@person.Id" title="Delete" class="btn btn-danger">Delete</a>
                </td>
            </tr>
        }
        </tbody>
    </table>
</div>

src/ISAT.Developer.Exam.Web/Views/Persons/part/fields.cshtml
@model ISAT.Developer.Exam.Web.Models.PersonViewModel

<div class="form-group">
    <label asp-for="FirstName" class="col-md-2 control-label"></label>
    @Html.TextBoxFor(model => model.FirstName, new { @class=Model.getClass })
    <span asp-validation-for="FirstName" class="text-danger"></span>
</div>
<div class="form-group">
    <label asp-for="LastName" class="col-md-2 control-label"></label>
    @Html.TextBoxFor(model => model.LastName, new { @class=Model.getClass })
    <span asp-validation-for="LastName" class="text-danger"></span>
</div>
<div class="form-group">
    <label asp-for="Email" class="col-md-2 control-label"></label>
    @Html.TextBoxFor(model => model.Email, new { @class=Model.getClass })
    <span asp-validation-for="Email" class="text-danger"></span>
</div>
<div class="form-group">
    <label asp-for="Age" class="col-md-2 control-label"></label>
    @Html.TextBoxFor(model => model.Age, new { @class=Model.getClass })
    <span asp-validation-for="Age" class="text-danger"></span>
</div>

src/ISAT.Developer.Exam.Web/Views/Persons/part/form.cshtml
@await Html.PartialAsync("heading.cshtml")

<div class="form-horizontal">
    <hr />
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>

    @await Html.PartialAsync("fields.cshtml")

    <div class="form-group">
        <div class="col-md-12">
            <input type="submit" value="@ViewData["action"]" class="btn btn-success" />
        </div>
    </div>
</div>

src/ISAT.Developer.Exam.Web/Views/Persons/part/heading.cshtml
<div class="row">
    <div class="col-sm">
        <h3>@ViewData["Title"]</h3>
    </div>
    <div class="col-sm">
    </div>
    <div class="col-sm">
        @Html.ActionLink("…Return to list", "Index", null, null, new { @class = "btn btn-info" })
    </div>
</div>

src/ISAT.Developer.Exam.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ISAT.Developer.Exam.Web</title>
    <link rel="stylesheet" href="~/css/site.min.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ISAT.Developer.Exam.Web</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Persons" asp-action="Index">Persons</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">About</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - ISAT.Developer.Exam.Web - 🜏
        </div>
    </footer>

    <script src="~/js/site.min.js" asp-append-version="true"></script>
    <script src="https://kit.fontawesome.com/da70d6d0bb.js" crossorigin="anonymous"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>